dependencies:
- name: queue
  version: 0.1.0
  repository: https://raw.githubusercontent.com/53555/helm-repo/master  #https://charts.bitnami.com/bitnami
- name: position-simulator
  version: 0.1.0
  repository: https://raw.githubusercontent.com/53555/helm-repo/master
- name: position-tracker
  version: 0.1.0
  repository: https://raw.githubusercontent.com/53555/helm-repo/master
- name: api-gateway
  version: 0.1.0
  repository: https://raw.githubusercontent.com/53555/helm-repo/master
- name: webapp
  version: 0.1.0
  repository: https://raw.githubusercontent.com/53555/helm-repo/master