namespace: prod

global:
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 80m
      memory: 128Mi
  probePath: /
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 90
    failureThreshold: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  envvar:
    profile: "production-microservice"
  terminationGracePeriodSeconds: 30

queue:
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 80m
      memory: 128Mi
  envvar:
    profile: "production-microservice"
  terminationGracePeriodSeconds: 30

position-simulator:
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 80m
      memory: 128Mi
  envvar:
    profile: "production-microservice"
  terminationGracePeriodSeconds: 30

position-tracker:
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 80m
      memory: 128Mi
  envvar:
    profile: "production-microservice"
  terminationGracePeriodSeconds: 30

api-gateway:
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 80m
      memory: 128Mi
  envvar:
    profile: "production-microservice"
  terminationGracePeriodSeconds: 30

webapp:
  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 80m
      memory: 128Mi
  envvar:
    profile: "production-microservice"
  terminationGracePeriodSeconds: 30