image:
  repository: richardchesterwood/k8s-fleetman-queue
  tag: release1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  externalPort: 80
  internalPort: 80
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
envvar:
  profile: "production-microservice"
terminationGracePeriodSeconds: 30

ingress:
  enabled: false
  host: prod.webapp.test.com

hpa:
  enabled: false
  minReplicas: 3
  maxReplicas: 6
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80

istio:
  enabled: false


